### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by missoxd** [mundipagg/magento-module#11]
Galera, queria saber se vocês pretendem (ou tem no roadmap) publicar esse módulo no [packagist](https://packagist.org/).

**Comment by felipebool** [comment]
Opa! Para o caso do Magento, o modman (https://github.com/colinmollenhour/modman) nos parece mais adequado. Você teve algum problema com ele ou com a instalação?

**Comment by missoxd** [comment]
Nenhum problema com o modman, perguntei mesmo porque nosso fluxo de desonvolvimento Magento é com composer. Usamos [esse](https://github.com/Cotya/magento-composer-installer) composer installer pra trabalhar com os módulos.

**Comment by philspbr** [comment]
+1 for composer file

**Comment by ThiagoBarradas** [comment]
@vitormattos @michelpl @felipebool como ficou o Packagist?

**Comment by missoxd** [comment]
Vi que colocaram o composer.json mas ainda não tem o packagist.
Mesmo assim quando colocamos ele como um repo standalone no composer.json ele não funciona por não jogar os arquivos pros lugares como ta no modman.
Acho que isso pode ser resolvido com o #93

**Comment by felipebool** [comment]
@missoxd, vou avaliar a solução proposta pelo @cadohr e resolvendo o problema aceitaremos o pull request.

**Comment by michelpl** [comment]
Nosso novo módulo para nossa nova API e suporte ao composer: https://github.com/mundipagg/magento
