### ISSUE TITLE
Descontos não estão sendo aplicados através de regras de promoção

### ISSUE THREAD

**Issue by richardschuler** [mundipagg/magento-module#115]
Olá. Notei que o módulo não está aplicando os descontos quando o mesmo é criado através das regras de promoção do Magento. O desconto no boleto só funciona se for inserido diretamente no campo que módulo oferece. 

Caso você deixe o campo em branco e tente usar o desconto através de regras, o desconto não é aplicado ao final da compra. No resumo do pedido no checkout ele é calculado mas ao finalizar o pedido, ele não é aplicado.

Aqui na empresa, corrigimos o BUG através do arquivo: **app/code/community/Uecommerce/Mundipagg/Model/Boleto.php**, comentando boa parte do código "MundipaggDiscounts".

Ele irá ignorar o campo de desconto do módulo e e aplicar o que estiver nas regras.

**Comment by michelpl** [comment]
Olá @richardschuler e obrigado pelo seu comentário!
Já corrigimos esse bug nas versões mais recentes do módulo.

Você pode atualizar e caso encontre algum outro problema pode entrar em contato novamente.
Também estamos abertos a pull requests, caso queira contribuir.

* Lembramos que toda e qualquer atualização envolve riscos e recomendamos que isso seja feito primeiramente em ambiente de TESTES.

Abçs.

**Comment by phillipesouza** [comment]
Olá @michelpl, estamos com o mesmo problema, a versão do módulo foi atualizada, porém ainda assim não aplica a Regra de Promoção.
