### ISSUE TITLE
Cancelamento do boleto/pedido 

### ISSUE THREAD

**Issue by cesaroito** [mundipagg/magento-module#135]
Olá,
Usamos a versão 2.13.03 do módulo. Gostaria de saber se tem como cancelar o boleto/pedido automaticamente após o vencimento do boleto e o mesmo não for pago.

Obrigado.

**Comment by michelpl** [comment]
Olá @cesaroito!
Infelizmente, como um boleto não pode ser cancelado junto ao banco, visto que você pode pagar um boleto mesmo após vencido, oferecer a funcionalidade de cancelamento automático passaria a falsa sensação de que também estamos cancelando a transação do "nosso" lado (gateway).

**Comment by cesaroito** [comment]
Olá Michel Lima,

Muito obrigado pela dica.
Abs,

Cesar Rodrigues
(11)4148-5981
(11)99958-9351
www.rcdesign.com.br


Em 18 de abril de 2018 10:40, Michel Lima <notifications@github.com>
escreveu:
