### ISSUE TITLE
Erro ao desinstalar o modulo

### ISSUE THREAD

**Issue by Leandro-marcel** [mundipagg/magento-module#146]
Estou com o seguinte erro quando vou editar algum produto logo depois de ter desinstalado o modulo.
podem me ajudar?

a:5:{i:0;s:99:"Modelo base "mundipagg/source_frequency" não encontrado para o atributo "mundipagg_frequency_enum"";i:1;s:3671:"#0 /home/lux/public_html/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(390): Mage::exception('Mage_Eav', 'Modelo base "mu...')
#1 /home/lux/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(201): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#2 /home/lux/public_html/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tab/Attributes.php(70): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset), Array)
#3 /home/lux/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(144): Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Attributes->_prepareForm()
#4 /home/lux/public_html/app/code/core/Mage/Core/Block/Abstract.php(922): Mage_Adminhtml_Block_Widget_Form->_beforeToHtml()
#5 /home/lux/public_html/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tabs.php(79): Mage_Core_Block_Abstract->toHtml()
#6 /home/lux/public_html/app/code/core/Mage/Core/Block/Abstract.php(297): Mage_Adminhtml_Block_Catalog_Product_Edit_Tabs->_prepareLayout()
#7 /home/lux/public_html/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Smartwave_All_Model_Core_Layout))
#8 /home/lux/public_html/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'product_tabs')
#9 /home/lux/public_html/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'product_tabs')
#10 /home/lux/public_html/app/code/local/Smartwave/All/Model/Core/Layout.php(40): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#11 /home/lux/public_html/app/code/core/Mage/Core/Model/Layout.php(205): Smartwave_All_Model_Core_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#12 /home/lux/public_html/app/code/local/Smartwave/All/Model/Core/Layout.php(31): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#13 /home/lux/public_html/app/code/core/Mage/Core/Model/Layout.php(210): Smartwave_All_Model_Core_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#14 /home/lux/public_html/app/code/local/Smartwave/All/Model/Core/Layout.php(31): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#15 /home/lux/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Smartwave_All_Model_Core_Layout->generateBlocks()
#16 /home/lux/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#17 /home/lux/public_html/app/code/core/Mage/Adminhtml/Controller/Action.php(285): Mage_Core_Controller_Varien_Action->loadLayout(Array, true, true)
#18 /home/lux/public_html/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(250): Mage_Adminhtml_Controller_Action->loadLayout(Array)
#19 /home/lux/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->editAction()
#20 /home/lux/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#21 /home/lux/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#22 /home/lux/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#23 /home/lux/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#24 /home/lux/public_html/index.php(83): Mage::run('', 'store')
#25 {main}";s:3:"url";s:84:"/index.php/admin/catalog_product/edit/id/24864/key/9c9b8cc7e9c9fd7d66717b21c79fb567/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by michelpl** [comment]
Isso acontece porque você deve ter deletado os arquivos manualmente. Assim, o processo de desinstalação do módulo não foi executado, deixando lixo no banco de dados.

Exclua os seguintes registros da tabela eav_attribute e o problema deve ser resolvido.

![image](https://user-images.githubusercontent.com/6605776/40550634-10edd01c-6011-11e8-983d-d9d7e4c51b67.png)
