### ISSUE TITLE
Cancelamento pelo magento

### ISSUE THREAD

**Issue by AndrewMarques** [mundipagg/magento-module#228]
Olá,

Ao cancelar o pedido no Magento (fazendo reembolso), isso é enviado para o gateway também? Não estou conseguindo reproduzir esse cenário... o cliente sempre tem que entrar no dashboard da Mundipagg pra fazer o reembolso.

Obrigado!

**Comment by michelpl** [comment]
@AndrewMarques, ele deve fazer o cancelamento sim.
Para que possamos dar o suporte correto, precisamos que você abra um chamado pelos nossos canais de suporte (suporte@mundipagg.com). Vamos precisar de informações que não podem ser publicadas aqui. 
Para adiantar, já pode abrir o chamado preenchendo a seguinte lista de informações:

Descrição do problema: Ao cancelar o pedido no Magento (fazendo reembolso), o pedido não é cancelado na Mundipagg. O cliente sempre tem que entrar no dashboard da Mundipagg pra fazer o reembolso.

Anexar ao case as seguintes informações:
1 - Versão do Módulo
2 - Versão do Magento
3 - Versão do PHP
5 - Onde o erro acontece? R: cancelamento de pedidos com reembolso
6 - Qual método de pagamento? Cartão, boleto, 2 cartões...
8 - Acontece em todos os pedidos com cancelamento?
10 - Enviar prints do histórico do pedido.
11 - Link de sua loja de staging/testes (se existir)
13 - IMPORTANTE: Anexar ARQUIVOS contidos na pasta "var/logs", dentro da pasta de instalação do magento.
