### ISSUE TITLE
Erro ao finalizar compra com CEP geral específico

### ISSUE THREAD

**Issue by WidecommerceDev** [mundipagg/magento-module#235]
Olá, boa tarde !

Estamos com um problema em um cliente em comum onde alguns clientes não conseguem finalizar compra, até o momento nos foi relatado que a questão ocorre apenas para transações no boleto.

Ao verificarmos os logs de retorno gerados, a mensagem de erro retornada é: ""00057- CEP DO SACADO INCORRETO".
Porém ao consultar os dados do CEP em diversos Web Service, os mesmos retornam os dados de Cidade e Estado, sendo assim um CEP geral.

O Cep digitado é 42840-000.

Segue arquivo de log que utilizamos como base.

**Comment by michelpl** [comment]
@WidecommerceDev os logs do módulo possuem informações de cliente e da loja que não podem ser colocados publicamente. Deletamos ele do seu comentário, porém o github mantém o histórico das conversas.
