### ISSUE TITLE
site off in magento 1.9

### ISSUE THREAD

**Issue by mlimasolucoes** [mundipagg/magento-module#247]
a:5:{i:0;s:313:"Error in file: "/srv/users/serverpilot/apps/saloon/public/app/code/community/Mundipagg/Paymentmodule/sql/mundipagg_paymentmodule_setup/install-0.1.0.php" - 

SQLSTATE[HY000]: General error: 1293 Incorrect table definition;
 there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause";
 i:1;s:1084:"#0 /srv/users/serverpilot/apps/saloon/public/app/code/core/Mage/Core/Model/Resource/Setup.php(

**Comment by michelpl** [comment]
Olá @mlimasolucoes. Para que possamos ajudá-lo, precisamos de mais informações. 
Favor enviar um e-mail para suporte@mundipagg.com anexando os seguintes dados:

Descrição do problema acompanhado de:

1 - Versão do Módulo
2 - Versão do Magento
3 - Versão do PHP
4 - Onde o erro acontece? Admin, checkout, cadastro do cliente...
5 - É possível reproduzir o erro? Como?
6 - Onde e como o erro é apresentado? Mensagem na tela, popup, modal...
7 - Link de sua loja de testes.
8 - Conteúdo da pasta var/logs.
