### ISSUE TITLE
Esse módulo vai funcionar com a nova API da Mundipagg ou será descontinuado em breve?

### ISSUE THREAD

**Issue by vinidade** [mundipagg/magento-module#253]
Olá,

Eu sei que aqui não é o lugar certo para isso, mas já procurei em vários lugares e falei com várias pessoas e não souberam me ajudar.
A Mundipagg anunciou que em breve vai descontinuar a velha API. A dúvida é: esse módulo não vai mais funcionar depois disso ou tem previsão para ele ser atualizado para a Nova API?

**Comment by michelpl** [comment]
Olá @vinidade, estamos com suporte somente para correção de bugs para este módulo. O para a nova api (https://github.com/mundipagg/magento) é o que desenvolvemos novas features e que mantemos mais atualizado.
Recomendamos que você utilize o novo.
