### ISSUE TITLE
Script do cartao não carrega:   Uncaught ReferenceError: OSCForm is not defined

### ISSUE THREAD

**Issue by brunocportugal** [mundipagg/magento-module#272]
Olá, bom dia. 

01 - O cartão de credito não está sendo processado pelo erro de Uncaught Reference abaixo e o script da Mundi não é carregado. Depois de tudo preenchido no checkout, clico no botao pra finalizar e vai direto pra pagina de falha sem capturar a compra. Conseguem dar uma olhada nessa incompatibilidade. JS não é o nosso expertise e só falta isso pra lançar a loja. 

02 - Outro problema é que a opção de salvar o cartão só aparece quando o cliente está logado.

Link do site .dev para reprodução do erro no checkout:  http://www.dev.ilovechaos.com.br/hitchcock-is-our-hero.html

Desde já agradeço a atenção!

OSCCheckoutModuleHandler.js:79 Uncaught ReferenceError: OSCForm is not defined
    at OSCCheckoutModuleHandler.setSavePaymentInterceptor (OSCCheckoutModuleHandler.js:79)
    at Object.MundiPagg.initPaymentMethod (paymentmodule.js:13)
    at HTMLDocument.<anonymous> ((index):1680)
    at c (jquery.min.js:4)
    at Object.fireWith [as resolveWith] (jquery.min.js:4)
    at Function.ready (jquery.min.js:4)
    at HTMLDocument.q (jquery.min.js:4)

**Comment by michelpl** [comment]
Olá @brunocportugal , tudo bem?
Esse caso está relacionado ao nosso novo módulo (https://github.com/mundipagg/magento), não esse.
Como foi respondido por e-mail, o nosso módulo não conseguiu achar o objecto OSCForm porque falta um trecho de código do próprio One Step na sua loja. Não conseguimos integrar com ele se não estiver com todo seu conteúdo original. 
Consigo te dar um suporte melhor via o atendimento da Mundipagg.
Estou fechando essa issue por não se tratar de um problema de nosso módulo.

Abs.
