### ISSUE TITLE
Compatibilidade com Magento 1.9.4.4  e php 7.2

### ISSUE THREAD

**Issue by diogolast** [mundipagg/magento-module#275]
Gostaria de saber se esse modulo já foi testado na última versão do magento e com o php7.2? Não estou conseguindo finalizar a compra, ele retorna o seguinte erro via boleto.

Exception: Notice: Undefined variable: securityCodes  in .../app/code/community/Uecommerce/Mundipagg/Model/Observer.php on line 56 in .../app/code/core/Mage/Core/functions.php:232

Caso tenha aberto a issue de forma incorreta, peço desculpas.

**Comment by GabrielDeveloper** [comment]
@diogolast essa issue já chegou pela nossa plataforma oficial de reports e já estamos trabalhando para simular e corrigir o erro.

Obrigado.
