### ISSUE TITLE
Pedidos por Boleto com status Holded

### ISSUE THREAD

**Issue by caci** [mundipagg/magento-module#29]
Eu tive um problema com pedidos gerados por Boleto que ficavam com status: Holded e ao tentar mudar para Processing gerava um erro no Magento. Versão do Magento utilizada: 1.9.3.1 | Versão do módulo Mundipagg: v2.11.01.

Para solucionar, alterei o arquivo:
app/code/community/Uecommerce/Mundipagg/Model/Observer.php 

Na linha 115:
$this->_updateStatus($event->getOrder(), Mage_Sales_Model_Order::STATE_HOLDED, true, $comment, false);

Mudei o status de HOLDED para NEW.

Só reportando aqui para caso alguém tenha tido o mesmo problema.

**Comment by michelpl** [comment]
Olá! Obrigado pelo feedback. 
Vamos verificar o problema, mas de qualquer forma, fique à vontade para fazer um pull request!
Toda contribuição é bem-vinda

**Comment by vitormattos** [comment]
Olá,

O status "on hold" é correto no fluxo de boleto.

Processing é quando gera a fatura.

on hold é enquanto está segurando o pedido para aguardar o pagamento.

Tem um gráfico com o [fluxo](https://i.stack.imgur.com/eF4H4.png) dos status que ajuda um pouco a compreender.

Encontrei também um [artigo](https://jn2.zendesk.com/hc/pt-br/articles/201777700-Entendendo-o-fluxo-do-status-de-pedido-no-Magento) interessante sobre este tema.

O módulo da MundiPagg faz a mudança automática de status do pedido via post de notificação após o boleto ser compensado.

Chegou a avaliar os logs do Magento ou os logs do servidor http?

**Comment by missoxd** [comment]
Olá,

Perfeito quanto ao "on hold" pertencer ao fluxo natural dos status do boleto.

Uma coisa que gostaria de ver com vocês é a utilização do método hold (Mage_Sales_Model_Order@hold), ao invés de colocar diretamente o status como holded, isso fará com que os campos "hold_before_status" e "hold_before_state" sejam preenchidos, posteriormente quando a order for liberada, os campos status e state serão preenchidos corretamente com os valores antigos.

Mudança direta no state e status:
- [Uecommerce_Mundipagg_Model_Observer:L101](https://github.com/mundipagg/magento-module/blob/v2.16.04/app/code/community/Uecommerce/Mundipagg/Model/Observer.php#L101);
- [Uecommerce_Mundipagg_Model_Observer:L26](https://github.com/mundipagg/magento-module/blob/v2.16.04/app/code/community/Uecommerce/Mundipagg/Model/Observer.php#L26);

Interessante lembrar do recebimento do POST de notificação, quando ele for recebido, caso a order esteja "on hold", seria interessante fazer o "unhold" (com o método Mage_Sales_Model_Order@unhold) antes de executar quaisquer ações nela, depois voltar o "hold".

Abraços

**Comment by michelpl** [comment]
Olá @missoxd, estamos validando as alterações. Avisamos no case quando tivermos a solução aplicada.

Abçs.

**Comment by zpvini** [comment]
Também tenho um cliente que está com problemas por conta desta falha na implementação.

O cliente deseja atualizar manualmente o status dos pedidos de boleto, sem a conciliação bancária, pois já possui essa rotina implementada no ERP e não pode "desviar" os arquivos de remessa fornecidos pelo banco.

Se tivessem utilizado os métodos originais do magento `hold()` e `unhold()` pra essa situação, o pedido poderia ser liberado por meio do botão no admin, mas como deram apenas um `setStatus('hold')` e `setState('hold')`, apenas o módulo da mundi (ou outro módulo a ser desenvolvido) consegue alterar o status do pedido.

Por favor, considerem a correção do @missoxd.

Abç

**Comment by michelpl** [comment]
@zpvini a solução já foi implementada.
