### ISSUE TITLE
Magento Connect no longer exists, README link is broken 

### ISSUE THREAD

**Issue by RuanAzevedo** [mundipagg/magento-module#57]
Magento Connect was discontinued, so the following link is broken:
<https://www.magentocommerce.com/magento-connect/mundipagg-payment-gateway.html>

The module can be migrated to the new Marketplace, check these links:

<https://magento.com/blog/magento-news/magento-connect-moving-marketplace>

<https://community.magento.com/t5/Magento-DevBlog/Magento-Connect-is-Moving-to-Marketplace/ba-p/73100>

**Comment by michelpl** [comment]
Já tínhamos verificado isso.
Estamos passando pelo processo de publicação, que é bem demorado.
Assim que tivermos o novo link, publicamos aqui no gitHub.
