### ISSUE TITLE
Cancelamento de Pedidos

### ISSUE THREAD

**Issue by lucasPiovesan** [mundipagg/magento-module#65]
Bom dia,

Estou tendo o seguinte problema:

 Pedidos são cancelados no painel da Mundipagg, porém na minha loja não. O módulo possui alguma funcionalidade assim ? De cancelar no painel da mundipagg e já enviar alguma notificação para minha loja cancelar o pedido também?

**Comment by michelpl** [comment]
Olá @lucasPiovesan, o módulo tem essa funcionalidade sim, chama-se post de notificação. 
O interessante é que você abra um ticket em nossa central para que o atendimento ao cliente verifique se a url da sua loja está configurada corretamente em nossa base.

**Comment by mariovalney** [comment]
Olá @michelpl 

Desculpe a intromissão, mas não consegui encontrar documentação sobre qual seria essa URL de notificação. Talvez estivesse no Magento Connect, mas poderia me indicar?

Seria `https://exemplo.com.br/mundipagg/standard/` ?

Abraços

**Comment by lucasPiovesan** [comment]
Então pra mim o passo foi que seria essa url:

https://exemplo.com.br/mundipagg/standard/success

Porém se olhar essa url é sempre chamada na finalização do pedido. Sempre carrega o último pedido da loja para cancelar. O que me gerou a dúvida, se só cancela no momento da compra, ou se depois de dias a mundipagg manda notificações a essa url para atualizar os status do pedido. É isso que acontece?

**Comment by mariovalney** [comment]
@lucasPiovesan verdade. 
Agora dei uma olhada no controller e vi que o `/success` trata e redireciona para `/cancel`, `/api`, Home e carrinho, dependendo da situação. Então acho que seria essa URL mesmo.

Boa sorte com seu problema.

**Comment by lucasPiovesan** [comment]
@mariovalney obrigado.

**Comment by lucasPiovesan** [comment]
@michelpl mas é na hora da compra, ou depois de dias também?

**Comment by michelpl** [comment]
Depois de dias também, toda vez que o status da transação de compra for alterada.

**Comment by lucasPiovesan** [comment]
Entendi, eu precisava ver essas requisições para minha loja, para entender o que houve. O atendimento me passou essa url, porém meus pedidos não alteram status. Pedi os logs ontem e até agora não tive retorno. Pra tentar entender o que houve.

**Comment by mariovalney** [comment]
@michelpl e qual padrão a Mundipagg deve mandar? XML  ou JSON?

Abraços

**Comment by lucasPiovesan** [comment]
Eu compreendi que a mundipagg envia os post de notificação, porém o módulo para magento da mundipagg tem isso implementado nele? Essa é minha dúvida, pois não adianta a mundipagg enviar, se o módulo para magento não está preparado. Por que digo isso, se olhar no arquivo do módulo app/code/community/Uecommerce/Mundipagg/controllers/StandartController.php e olhar a função successAction(), função na qual é chamada pela url cadastrada na mundipagg  (http://minhaloja.com.br/mundipagg/standard/success/), vai ver que ela não recebe nenhum parâmetro na requisição, seja ele POST ou GET para alterar status do pedido ou qualquer outra coisa. O que essa função faz é pegar o valor de uma variável de sessão, veja abaixo:

$session = Mage::getSingleton('checkout/session');
$approvalRequestSuccess = $session->getApprovalRequestSuccess();

Sendo uma variável de sessão ela só tem valor para quem está realizando a compra na loja, ou seja o cliente que comprou. Então se eu alterar os status e mandar a notificação pelo painel da mundipagg nada vai acontecer, porque a variável de sessão é vinculado ao cliente que realizou a compra, e não as notificações da mundipagg, sendo assim nunca fará nada esse método sendo chamado por vocês que alegam que é ele que altera o status. Ele até altera o status, porém no momento da finalização da compra onde eu tenho o valor da minha variável de sessão dependendo do retorno da mundipagg, depois disso pelo que vi não. Posso estar enganado, poderiam me ajudar a entender?

**Comment by michelpl** [comment]
É essa url mesmo. Infelizmente foi utilizado a mesma rota pra fazer duas coisas diferentes. 
O responsável por processar o post de notificação é o método processOrder() na linha 385 do StandardController.php 

```
           $postData = $this->getRequest()->getPost();
            $api = Mage::getModel('mundipagg/api');

            // Process order
            $result = $api->processOrder($postData);
```

Você não precisa configurar nada do seu lado pra receber as atualizações dos pedidos.

**Comment by lucasPiovesan** [comment]
@michelpl entendi, realmente é nesse local. Agora consigo testar melhor.
