### ISSUE TITLE
preventSaving atrapalhando o processo do checkout

### ISSUE THREAD

**Issue by ebanolopes** [mundipagg/magento-module#67]
Pessoal, os métodos do módulo possuem nele as chamadas abaixo. Isto atrapalho o processo do checkout, interferindo aonde o método não deveria interferir, pois impede o salvamento de qualquer informação na cotação/carrinho (objeto quote) que esteja no mesmo request.

`$info->getQuote()->preventSaving();`

Abaixo print com as localizações do código dentro dos métodos do módulo. Sugiro que revisem o motivo de ter esta chamada aí e tratem de outra forma para que não interfira em outros processos externos ao módulo.

<img width="884" alt="captura de tela 2017-10-21 as 19 01 11" src="https://user-images.githubusercontent.com/997569/31855926-f1546148-b693-11e7-90fa-03f1511b892a.png">

### Exemplo de como isto causa problemas
**Cenário**: checkout de um passo só, no caso estou usando o da AheadWorks, mas acontece com outros também. A loja possui uma regra de promoção de carrinho, que dá 10% de desconto no boleto bancário.
1. No checkout, seleciona-se o método Boleto Bancário do módulo da MundiPagg. O checkout tenta, mas não consegue salvar que o método de pagamento escolhido foi boleto bancário, por causa do preventSaving. O desconto de 10% é aplicado e exibido no resumo da compra.
2. Após isto escolher trocar o método de envio

**Resultado**: os valores apresentados no resumo da compra não possuem o desconto à vista, pois ao processar a troca do método de pagamento não está selecionado a forma de pagamento, pois não foi salva na cotação

**Comment by michelpl** [comment]
Olá Ébano. Já tínhamos identificado esse problema. Estamos fazendo as correções.
Obrigado mais uma vez pela contribuição.

**Comment by ebanolopes** [comment]
Legal, @michelpl !! Tem ideia de quando deve ser liberada versão com esta correção? Se tiver, é bom pra eu tomar ou não uma ação internamente. Obrigado.

**Comment by michelpl** [comment]
Não deve demorar muito não. O problema é que temos que validar diversos fluxos como, cupons de desconto, desconto por tipo de pagamento, recorrência e interação com outros métodos de pagamentoml.

**Comment by felipebool** [comment]
Olá, @ebanolopes, como o @michelpl disse, existem diversos fluxos que precisam ser validados antes da remoção da chamada do preventSaving nos diversos pontos que você apresentou. Estou trabalhando nestas validações agora e tão logo tenhamos uma nova versão eu aviso aqui.

**Comment by michelpl** [comment]
Resolvido! Nova versão com isso removido.
