### ISSUE TITLE
Fatal error ao fazer login no admin

### ISSUE THREAD

**Issue by ebanolopes** [mundipagg/magento-module#81]
Estou usando a versão 2.13.02 e toda vez que é feito login no admin o módulo da Mundipagg gera o erro abaixo:

> [07-Nov-2017 12:05:11 UTC] PHP Fatal error:  Cannot use object of type stdClass as array in app/code/community/Uecommerce/Mundipagg/Model/Observer.php on line 773

A linha 773 é esta e não foi mudada na versão atual do repositório:

`return str_replace("v", "", $response[0]->tag_name);`

Podem ajustar, por favor?

E uma sugestão: mover esta verificação para um observer, porque algumas vezes só as lojas que tem o módulo da MundiPagg ficam muito lentas pra fazer o login, por causa do CURL que é chamado pra ver a versão.

**Comment by michelpl** [comment]
Olá Ebano! Já subimos uma versão com a correção, mas se você já quiser alterar aí é só fazer o seguinte:

Alterar a linha 756 do arquivo app/code/community/Uecommerce/Mundipagg/Model/Observer.php
de: $url = "https://api.github.com/repos/mundipagg/magento.integracao/releases";
para: $url = "https://api.github.com/repos/mundipagg/magento-module/releases";

Não entendi a sua sugestão. Esse código já fica em um Observer. Tem algo que possa ser melhorado?

**Comment by ebanolopes** [comment]
Legal, Michel! :) A minha sugestão, na verdade escrevi errado. A sugestão é mover para o cron ao invés de um observer em um evento que impacte na experiência do usuário.
