### ISSUE TITLE
Não consigo visualizar mais os boletos pelo admin do magento.

### ISSUE THREAD

**Issue by brpaoli** [mundipagg/magento-module#82]
```
Toda vez que clico no link imprimir boleto agora, sou redirecionado para a página do pedido novamente.


Please use the following template to submit your issue. 
Following this template will allow us to quickly investigate and help you with your issue. 
Please be aware that issues which do not conform to this template may be closed. 

DO NOT FORGET TO REMOVE THIS BLOCK
```

### Status

BUG REPORT / TASK

### Checklist

Add checklist if this is a task

- [x] Add slack integration
- [_] Support xyz 

### Steps

1. First step
2. Second step
3. Third step

### Expected behaviour

How do you think the program should work? Add screenshots and code blocks if necessary.

### Actual behaviour

How does the program work in its current state?

### Environment

You may write here the specifications like the version of the project, services, operating system, or hardware if applicable.

### Logs / Stack trace

```
Insert your log/stack trace here
```

**Comment by felipebool** [comment]
Resolvido na última versão

https://github.com/mundipagg/magento-module/releases/tag/v2.13.08
