### ISSUE TITLE
Função com erros

### ISSUE THREAD

**Issue by tfmlinkweb** [mundipagg/magento-module#83]
Por favor a função  private function getRepoVersion localizada em /code/community/Uecommerce/Mundipagg/Model/Observer.php linha 773, esta impossibilitando a login no admin.
Alguma previsão para contornar este erro?

**Comment by michelpl** [comment]
Olá. Já foi corrigido na versão atual.
Atualize o módulo em sua loja que o problema será resolvido.
Lembramos que toda atualização envolve riscos, por isso, atualize primeiramente sm ambiente de HOMOLOGAÇÃO.
