### ISSUE TITLE
Captura automática para pedidos com dois cartões

### ISSUE THREAD

**Issue by lucasPiovesan** [mundipagg/magento-module#84]
Pessoal nas configurações do módulo eu tenho um campo chamado "Ação de Pagamento" onde eu escolho entre "AuthAndCapture" e "AuthOnly". 

Quando deixo a opção AuthAndCapture e faço uma compra no cartão de crédito normal, o mesmo é capturado automáticamente na mundipagg.

Porém se eu deixar essa configuração e fizer um pedido com a opção de de dois cartões, meu pedido entra como autorizado apenas na mundipagg, sendo que deveria também ser capturado de acordo com a configuração que deixei habilitado.

A opção de dois cartões possui essa funcionalidade de autorizar e capturar?

**Comment by michelpl** [comment]
Olá @lucasPiovesan!
Lançamos uma atualização com essa correção. O problema de vocês ainda continua?

Abçs
