### ISSUE TITLE
Geração automatica de invoice por cartao.

### ISSUE THREAD

**Issue by tfmlinkweb** [mundipagg/magento-module#85]
Apos realizar alguns testes notei que apos autorizada uma compra pelo modulo da mindipagg é gerado uma invoice automatica, qual a funcao eu devo comentar para que nao seja  gerada essa invoice?
Isto esta afetando a regra de negocio do meu cliente.

Obrigado

**Comment by michelpl** [comment]
Olá @tfmlinkweb. Desculpe por não ter respondido sua dúvida.
Nosso canal oficial de suporte é o suporte@mundipagg.com

Conseguiu resolver o problema do cliente?
Se não, consegue explicar melhor? O fluxo normal de pagamento é esse mesmo. Comentar algum trecho do código pode implicar sérios problemas na hora de capturar uma transação
