### ISSUE TITLE
Pedido não autorizado

### ISSUE THREAD

**Issue by lucasPiovesan** [mundipagg/magento-module#86]
Quando realizo um pedido por cartão de crédito, e o mesmo não é autorizado em minha loja o pedido entra como cancelado, porém na mundipagg o pedido não chega a entrar.

É essa ação mesmo que deve acontecer?

**Comment by michelpl** [comment]
Não é não. Mesmo não autorizada, a transação deve ser criada aqui. Você pode entrar em contato com suporte@mundipagg.com pra que a gente possa te dar um suporte melhor. Existe uma série de informações que precisamo e que não podem ser passadas por aqui.

* Temos um issue template para criação de novas issues https://github.com/mundipagg/magento-module/blob/master/ISSUE-TEMPLATE.md
